name       : pylint
version    : 1.8.1
release    : 4
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-1.8.1.tar.gz : 570d4d1efa2ffa6e4ca283e0ffb28cdcc6cb048dd12db084eaea76d3741d7db2
license    : GPL-2.0
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python-3.5)
    - pytest-runner
    - python-setuptools
rundeps    :
    - mccabe
    - python-astroid
    - python-configparser
    - python-isort
    - python-logilab-common
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
