name       : pylint
version    : 2.13.9
release    : 30
source     :
    - https://github.com/PyCQA/pylint/archive/refs/tags/v2.13.9.tar.gz : e62e24d8162ec191e3f4a24fd85a8c4d37a3fd8b27b315ec6a65ad12b62c0aa6
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    Pylint is a Python static code analysis tool which looks for programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - python-astroid
    - python-dill
    - python-isort
    - python-platformdirs
    - python-pytest-benchmark
    - python-pytest-timeout
    - python-tomli
rundeps    :
    - mccabe
    - python-astroid
    - python-dill
    - python-isort
    - python-platformdirs
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Need to undeprecate and udpate python-gitpython and deps
    rm py3build/tests/{primer/test_primer_external.py,testutils/test_package_to_lint.py}
    %python3_test pytest3 -v -k 'not test_do_not_import_files_from_local_directory_with_pythonpath'
