name       : pylint
version    : 1.8.2
release    : 5
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-1.8.2.tar.gz : 22b9481475bf09c0d4c415cdf33df1a5a11d7170c4e72a22be0e4e07be3124b2
license    : GPL-2.0
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python-3.5)
    - pytest-runner
    - python-setuptools
rundeps    :
    - mccabe
    - python-astroid
    - python-configparser
    - python-isort
    - python-logilab-common
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
