name       : pylint
version    : 1.7.4
release    : 3
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-1.7.4.tar.gz : c333219798cdf322e15edfa60129e795a45e5c9c806a79c61508b40a2310b7b3
license    : GPL-2.0
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python-3.5)
    - pytest-runner
    - python-setuptools
rundeps    :
    - mccabe
    - python-astroid
    - python-configparser
    - python-isort
    - python-logilab-common
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
