name       : pylint
version    : 2.9.1
release    : 21
source     :
    - https://github.com/PyCQA/pylint/archive/refs/tags/v2.9.1.tar.gz : c1d290149c50f13966ea52b1d72b4131d4124733a9c0c1347f588e0a091fd531
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - python-astroid
    - python-isort
    - python-pytest-benchmark
    - python-toml
rundeps    :
    - mccabe
    - python-astroid
    - python-isort
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_do_not_import_files_from_local_directory_with_pythonpath'
