name       : pylint
version    : 2.11.1
release    : 23
source     :
    - https://github.com/PyCQA/pylint/archive/refs/tags/v2.11.1.tar.gz : b797b4906068c616db2aaf364e56506d42b130474e98a16a0e2b9eb72fa0b1b7
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - python-astroid
    - python-isort
    - python-platformdirs
    - python-pytest-benchmark
    - python-toml
rundeps    :
    - mccabe
    - python-astroid
    - python-isort
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_do_not_import_files_from_local_directory_with_pythonpath'
