name       : pylint
version    : 2.6.0
release    : 19
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-2.6.0.tar.gz : 45a9ea92ead1fd91d725915ad4c40f2d73c1ebd553afb263a31340bf6a39cb7a
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - python-astroid
    - python-isort
    - python-pytest-benchmark
    - python-toml
rundeps    :
    - mccabe
    - python-astroid
    - python-isort
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : | 
    %python3_test py.test3 -v
