name       : pylint
version    : 1.8.3
release    : 7
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-1.8.3.tar.gz : d1ff1a47e8518c9c4827a7e003115870e8c524c7ed761063b325c3c60e172990
license    : GPL-2.0
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pytest-runner
    - python-astroid
    - python-configparser
    - python-isort
    - python-setuptools
rundeps    :
    - mccabe
    - python-astroid
    - python-configparser
    - python-isort
    - python-logilab-common
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
check     : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py pytest
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py pytest
    popd
