name       : pylint
version    : 2.15.9
release    : 33
source     :
    - https://github.com/PyCQA/pylint/archive/refs/tags/v2.15.9.tar.gz : c50d89b74aadca416b7003ec924780598ac59307a82c6692bec59ae83dbca7e9
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Pylint is a static code analyser for Python
description: |
    Pylint is a Python static code analysis tool which looks for programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions.
builddeps  :
    - python-build
    - python-installer
    - mccabe                   # check
    - python-astroid           # check
    - python-dill              # check
    - python-isort             # check
    - python-packaging
    - python-platformdirs      # check
    - python-tomlkit           # check
    - python-typing-extensions # check
    - python-pytest-timeout    # check
    - python-pytest-benchmark  # check
    - python-wheel
rundeps    :
    - mccabe
    - python-astroid
    - python-dill
    - python-isort
    - python-platformdirs
    - python-tomli
    - python-tomlkit
setup      : |
    sed -i -e "s|setuptools~=62.6|setuptools|g" pyproject.toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Need to undeprecate and udpate python-gitpython and deps
    rm py3build/tests/testutils/_primer/{test_package_to_lint.py,test_primer.py}
    rm py3build/tests/primer/test_primer_external.py

    # skip failing tests
    skiptest='test_do_not_import_files_from_local_directory'
    skiptest+=' or test_functional[missing_timeout]'
    skiptest+=' or test__test_environ_pythonpath_no_arg'
    skiptest+=' or test_linter_with_unpickleable_plugins_is_pickleable'
    %python3_test pytest3 -v -k "not (${skiptest})"
