name       : pylint
version    : 1.7.2
release    : 1
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-1.7.2.tar.gz : b7666e93ba77c7dbb89f05ad94101440494d8e58303a1cb9c8af06073f0bf657
license    : GPL-2.0
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python-3.5)
    - pytest-runner
    - python-setuptools
rundeps    :
    - mccabe
    - python-astroid
    - python-isort
    - python-logilab-common
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
