name       : pylint
version    : 2.0.1
release    : 9
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-2.0.1.tar.gz : 0031a6d05a491c8c39f7ec4ce598a47da99fc02ad4f676e485db2a700460cbc1
license    : GPL-2.0-only
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pytest-runner
    - python-isort
    - python-astroid
rundeps    :
    - mccabe
    - python-isort
    - python-astroid
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py pytest
    popd
