name       : pylint
version    : 2.6.2
release    : 20
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-2.6.2.tar.gz : 721403119b6ca12234f75b7c01ffe7f0510e3995170ddce61e8d5801e27b6aeb
homepage   : https://github.com/PyCQA/pylint
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - python-astroid
    - python-isort
    - python-pytest-benchmark
    - python-toml
rundeps    :
    - mccabe
    - python-astroid
    - python-isort
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
