name       : pylint
version    : 2.5.0
release    : 18
source     :
    - https://github.com/PyCQA/pylint/archive/pylint-2.5.0.tar.gz : ac7f4bbbe672ac9c6dbb78a7efefb4110f90a1c8768229191df38a16b6357605
license    : GPL-2.0-or-later
component  : programming.tools
summary    : A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells
description: |
    A Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pytest-runner
    - python-isort
    - python-astroid
    - python-toml
rundeps    :
    - mccabe
    - python-isort
    - python-astroid
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : | testing against installed version, despite macro.
#    %python3_test py.test3 -v -k 'not iterable_context_py36'
